package com.rain6.cxf.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-02-27T14:44:08.238+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebServiceClient(name = "TestWebServiceImplService", 
                  wsdlLocation = "http://localhost:8092/webservice/testService?wsdl",
                  targetNamespace = "http://service.cxf.rain6.com/") 
public class TestWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cxf.rain6.com/", "TestWebServiceImplService");
    public final static QName TestWebServiceImplPort = new QName("http://service.cxf.rain6.com/", "TestWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8092/webservice/testService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8092/webservice/testService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort() {
        return super.getPort(TestWebServiceImplPort, TestWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServiceImplPort")
    public TestWebService getTestWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TestWebServiceImplPort, TestWebService.class, features);
    }

}
